### ISSUE TITLE
CSS Properties link on your homepage is broken

### ISSUE THREAD

**Issue by jelkner** [PeterY18/itd210#1]
The link to CSS Properties that you have on the homepage is broken.  I suggest removing it and putting all your GDW lessons under "Getting Down with HTML/CSS Work".

**Comment by peteryn** [comment]
Dear Jeff,

Sorry about that. I meant to remove it and forgot about it. I also added
display2, positioning, and grid2 to the index page within gdw that I forgot
to add. Enjoy the rest of your weekend.

-Peter
